examples/GPRSPing/GPRSPing.ino
examples/GPRSUdpNtpClient/GPRSUdpNtpClient.ino
examples/GsmLocation/GsmLocation.ino
examples/GsmSSLWebClient/GsmSSLWebClient.ino
examples/GsmWebClient/GsmWebClient.ino
examples/GsmWebServer/GsmWebServer.ino
examples/MakeVoiceCall/MakeVoiceCall.ino
examples/ReceiveSMS/ReceiveSMS.ino
examples/ReceiveVoiceCall/ReceiveVoiceCall.ino
examples/SendSMS/SendSMS.ino
examples/Tools/GsmScanNetworks/GsmScanNetworks.ino
examples/Tools/TestWebServer/TestWebServer.ino

@cmaglie as discussed:
- Avoid using double negatives in example sketches (`!notConnected`)
- Replaces bit wise `&` with logical `&&`

Example sketches: Avoid double negatives and correct &'s to &&

---

src/GSMClient.cpp
src/GSMClient.h
src/GSMServer.cpp
src/GSMServer.h
src/GSMUdp.cpp
src/GSMUdp.h
src/Modem.h

I think this will help with #10 and #11.
From section 25.12.1 of the u-blox AT command manual:
> For the TCP socket type the URC +UUSORD: <socket>,<length> notifies the data bytes available for reading, either when buffer is empty and new data arrives or after a partial read by the user.
and section:
>  The URC +UUSORF: <socket>,<length> (or also +UUSORD: <socket>,<length>) notifies that new data is available for reading, either when new data arrives or after a partial read by the user for the socket. 
These change leverage these URC's instead of using the `AT+USORD` or `AT+USORF` commands to poll for data available. So, the modem is not hammered with commands.
The `GSMWebClient` example is now > 50% faster in my tests (~9s vs ~19s).

Use socket URC's to determine available socket data

---

src/GSMPIN.cpp
src/GSMVoiceCall.cpp
src/Modem.cpp

When low power mode, the module needs a bit more time to wake up even though CTS is set. This PR adds a 5ms delay before sending the AT command in low power mode.
I've also made some changes to correctly handle `millis()` rollover scenarios, as @cmaglie mentioned when he looked at the code.

Low power fixes

---

src/GPRS.cpp
src/GPRS.h
src/GSM.cpp
src/GSMServer.cpp
src/GSMUdp.cpp

This is a proposal for issue #15. Changes include:
* correcting `GSM::isAccessAlive()` to report current registration status
* adding timeout for `GPRS::ping(...)`
* new `GPRS::status` API to return the current status `IDLE` or `GPRS_READY`. The status is updated on `GPRS::attachGPRS(...)`, `GPRS::detachGPRS(...)` or when a `+UUPSDD` is received.
It's still not ready, as it can't detect the scenario where you manually disconnect the antenna and the board loses signal.
cc/ @alvarolb @FrancMunoz @w3p706

Add new GPRS::status() API

---

src/GSMClient.cpp

call of the function` size_t GSMClient::write(const uint8_t* buf, size_t size)` instead of `size_t GSMClient::write(const uint8_t* buf)` in `GSMClient::write(uint8_t c)`

Fix GSMClient::write(uint8_t c)

---

examples/GPRSPing/GPRSPing.ino
examples/GPRSUdpNtpClient/GPRSUdpNtpClient.ino
examples/GsmLocation/GsmLocation.ino
examples/GsmSSLWebClient/GsmSSLWebClient.ino
examples/GsmWebClient/GsmWebClient.ino
examples/GsmWebServer/GsmWebServer.ino
examples/MakeVoiceCall/MakeVoiceCall.ino
examples/ReceiveSMS/ReceiveSMS.ino
examples/ReceiveVoiceCall/ReceiveVoiceCall.ino
examples/SendSMS/SendSMS.ino
examples/Tools/BandManagement/BandManagement.ino
examples/Tools/GsmScanNetworks/GsmScanNetworks.ino
examples/Tools/PinManagement/PinManagement.ino
examples/Tools/TestGPRS/TestGPRS.ino
examples/Tools/TestWebServer/TestWebServer.ino

Replace boolean type with bool in examples
This is part of a move to encourage use of the standard bool type over Arduino's non-standard boolean type alias.
As approved by cmaglie: https://github.com/arduino/Arduino/issues/6657#issuecomment-355597633

Replace boolean type with bool in examples

---

src/GSMClient.cpp
src/GSMClient.h

The last chunk of data received on the socket before it closes was not returned. The URC caused the socket to be in the closed state.
Related to #44.
sketch to test with
```arduino
#include "arduino_secrets.h"
#include "MKRGSM.h"
#include "ArduinoHttpClient.h"
//Secrets below kept in secrets tab (arduino_secrets.h)
const char PINNUMBER[] = SECRET_PINNUMBER;
// APN data
const char GPRS_APN[] = SECRET_GPRS_APN;
const char GPRS_LOGIN[] = SECRET_GPRS_LOGIN;
const char GPRS_PASSWORD[] = SECRET_GPRS_PASSWORD;
GSM gsmAccess(true); // Cellular modem instance
GPRS gprs;     // With TCP/IP based communication enabled
GSMSSLClient gsm; // Accessible by Arduino sketch as a standard Stream class
// Create an HTTP client on top of all this
char server[] = "arduino.cc";
char path[] = "/asciilogo.txt"; …
```

Fix some regressions introduced by the new socket buffer

---

src/GSMClient.cpp

Set GSMClient state to CLIENT_STATE_IDLE at the beginning of the stop() method so that the state is reset even if the _socket value is -1.  This is necessary because the state can be left in CLIENT_STATE_WAIT_CREATE_SOCKET_RESPONSE state with _socket = -1 if the AT+USOCR= command hangs.

Reset GSMClient state at the beginning of stop() method

---

src/GSM.cpp

Added GSM status check in shutdown() function to avoid freeze made by a double calling of GSM::suhutdown() API
cc/ @sandeepmistry

Add GSM status check

---

src/GSM_SMS.cpp

Added a ```+1``` in the available API's return to avoid that SMS with only 1 char are discarded
Resolve https://github.com/arduino-libraries/MKRGSM/issues/63#event-1977412413
cc/ @sandeepmistry just tested ready to merge

Fix one char SMS receiving

---

src/GSMClient.cpp

As suggested by @winijenh in #75.

Fix GSMClient::write for write lengths of > 256

---

keywords.txt
src/GSMModem.cpp
src/GSMModem.h

- implemented `getICCID()` method to retrieve SIM ICCID number as a String

Method to retrieve SIM's ICCID

---

src/Modem.cpp
src/Modem.h

Sometimes it is useful to slow down modem baud rate and send debug info somewhere else. Additions do not change default behaviour (baud rate 921600 and Serial as debug output)

Add setBaudRate and setDebugStream to Modem class

---

src/GSMClient.cpp

From section 26.3 in the AT command manual, 10 should be used to enable SNI.

GSMSSLClient: correct AT+USECPRF command usage

---

src/GSM.cpp

from @facchinm :
compilation fails due to
`error: 'strptime' was not declared in this scope` 
which is in fact fixed by `_XOPEN_SOURCE patch`

fix compiler complaint about `strptime`

---

src/GSMUdp.cpp

This changefix the  negative value returned by GSMUDP::available()
fix: https://github.com/arduino-libraries/MKRGSM/issues/105 and https://github.com/arduino-libraries/MKRGSM/issues/106
cc:/ @facchinm i have check and seems that the UDP's buffer is not a ring buffer than this change should be enough to fix this two issue could simple take a look if i'm right about the buffer?

Changed Available return's values

---

src/GSMFileUtils.cpp
src/GSMFileUtils.h

Empty/memset `GSMFileUtils::read()` return parameters before use.
Fixes unwanted appending of contents when reusing return parameters.

Empty FileUtils::read return variables before use

---

src/GPRS.cpp

I noticed that _state was being set to "ERROR" in the case GPRS_STATE_WAIT_SET_DYNAMIC_IP_RESPONSE instead of setting _status to "ERROR".

Fix incorrect variable assignment

---

src/Modem.cpp
src/Modem.h

Hi, the current code will mis-interpret an SMS response for any SMS with the content "OK".
In this case the AT command response will contain "+CMGL: ...\r\nOK\r\n" which will be caught in MODEM::poll() during the readout of the response, and break the interpreter. 
The pull request contains special handling of "+CMGL:" responses.
I tried to make the change as small as possible, and with as small runtime overhead as possible. It checks if the response contains an SMS response once, and if not, continues with the old code.

Handle SMS responses 

---

src/Modem.cpp

As mentioned before by others, the delay(100) is confirmed by the ublox datasheet but sometimes the modem hangs during the startup with this value. With a delay(200), it starts.

A little more time for the modem to switch baud rate

---

docs/api.md

the ### `voice.readDTMF()` was shown improperly. I think I fixed it with this PR :)

updated the file to show all examples

---

examples/SSLCertificateManagement/SSLCertificateManagement.ino

Missing letter 's' when calling function 'eraseAllCertificates'.

Fixing CI build of examples/eraseAllCertificates:
